config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :projects do
    resources :tickets, only: [:index, :new, :create]
  end

  resources :tickets, only: [:show, :edit, :update, :destroy] do
    resources :messages, only: [:index, :show, :new, :create]
  end

  resources :messages, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :ticket
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tickets, dependent: :destroy
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  has_many :messages, dependent: :destroy

  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_ticket, only: %i[new create destroy]

  def index
    @messages = Message.all
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.ticket = @ticket
    if @message.save
      redirect_to ticket_path(@ticket)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @message.update(message_params)
    redirect_to ticket_path(@ticket)
  end

  def destroy
    @message.destroy
    redirect_to ticket_path(@ticket), status: :see_other
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
    @tickets = Ticket.where(project: @project.id)
    @new_ticket = Ticket.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project.destroy
    redirect_to projects_path, status: :see_other
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :url)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: %i[new create]

  def index
    @tickets = Ticket.all
  end

  def show
    @messages = Message.where(ticket: @ticket.id)
    @message = Message.new
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.project = @project
    @ticket.statut = "OPEN"
    if @ticket.save
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @ticket.update(ticket_params)
    redirect_to project_path(@ticket.project)
  end

  def destroy
    @ticket.destroy
    redirect_to project_path(@ticket.project), status: :see_other
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def ticket_params
    params.require(:ticket).permit(:description, :statut, :priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketsManager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/projects/_form.html.erb
<%= simple_form_for (project) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :url %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>all projects</h1>


<%= link_to "add a new project", new_project_path %>

<ul>
  <% @projects.each do | project | %>
    <li><%= link_to project.name, project_path(project) %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

<h1>New Project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1>Projects#show</h1>

<% if @project.url.nil? %>
  <h2><%= @project.name %></h2>
<% else %>
  <h2><%= link_to @project.name, @project.url%></h2>
<% end %>

<p><%= @project.description %></p>

<p>tickets</p>
<ul>
  <% @tickets.each do |ticket|%>
  <li>
    <%= link_to ticket.description, ticket_path(ticket) %> - <%= ticket.statut %>
    <div>
      <%= simple_form_for (ticket) do |f| %>
        <%# <%= f.input :statut %>
        <%= f.button :statut, "Custom Button Text" %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
    <button data-controller="tickets" data-action="click->tickets#changeTicketStatut">click</button>
  </li>
  <% end %>
</ul>

<p>create a new ticket</p>
<%= simple_form_for [@project, @new_ticket] do |f| %>
  <%= f.input :description %>
  <%= f.input :priority %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/tickets/_form_tickets.html.erb
<%= simple_form_for [project, ticket] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :url %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Tickets#edit</h1>
<p>Find me in app/views/tickets/edit.html.erb</p>

app/views/tickets/index.html.erb
<h1>Tickets#index</h1>
<p>Find me in app/views/tickets/index.html.erb</p>

app/views/tickets/new.html.erb
<h1>Tickets#new</h1>
<p>Find me in app/views/tickets/new.html.erb</p>
<h1>New review</h1>
<%= simple_form_for [@project, @ticket] do |f| %>
  <%= f.input :description %>
  <%= f.input :statut %>
  <%= f.input :priority %>
  <%= f.submit "Submit ticket", class: "btn btn-primary" %>
<% end %>

app/views/tickets/show.html.erb
<h1>Tickets#show</h1>
<p>Find me in app/views/tickets/show.html.erb</p>
<%= link_to "back", @ticket.project  %>

<h2><%= @ticket.description %></h2>
<p>status: <%= @ticket.statut %></p>
<p>priority: <%= @ticket.priority %></p>

<p>Messages:</p>
<ul>
  <% @messages.each do |message| %>
  <li>
    <%= message.content %>
  </li>
  <% end %>
</ul>

<p>leave a message</p>
<%= simple_form_for [@ticket, @message] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>